package com.sanmer.mrepo.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val cyan_light_primary = Color(0xFF006876)
private val cyan_light_onPrimary = Color(0xFFFFFFFF)
private val cyan_light_primaryContainer = Color(0xFFA1EFFF)
private val cyan_light_onPrimaryContainer = Color(0xFF001F25)
private val cyan_light_secondary = Color(0xFF4A6268)
private val cyan_light_onSecondary = Color(0xFFFFFFFF)
private val cyan_light_secondaryContainer = Color(0xFFCDE7ED)
private val cyan_light_onSecondaryContainer = Color(0xFF051F23)
private val cyan_light_tertiary = Color(0xFF545D7E)
private val cyan_light_onTertiary = Color(0xFFFFFFFF)
private val cyan_light_tertiaryContainer = Color(0xFFDBE1FF)
private val cyan_light_onTertiaryContainer = Color(0xFF101A37)
private val cyan_light_error = Color(0xFFBA1A1A)
private val cyan_light_errorContainer = Color(0xFFFFDAD6)
private val cyan_light_onError = Color(0xFFFFFFFF)
private val cyan_light_onErrorContainer = Color(0xFF410002)
private val cyan_light_background = Color(0xFFFBFCFD)
private val cyan_light_onBackground = Color(0xFF191C1D)
private val cyan_light_surface = Color(0xFFFBFCFD)
private val cyan_light_onSurface = Color(0xFF191C1D)
private val cyan_light_surfaceVariant = Color(0xFFDBE4E6)
private val cyan_light_onSurfaceVariant = Color(0xFF3F484A)
private val cyan_light_outline = Color(0xFF6F797B)
private val cyan_light_inverseOnSurface = Color(0xFFEFF1F2)
private val cyan_light_inverseSurface = Color(0xFF2E3132)
private val cyan_light_inversePrimary = Color(0xFF44D8F1)
private val cyan_light_shadow = Color(0xFF000000)
private val cyan_light_surfaceTint = Color(0xFF006876)

private val cyan_dark_primary = Color(0xFF44D8F1)
private val cyan_dark_onPrimary = Color(0xFF00363E)
private val cyan_dark_primaryContainer = Color(0xFF004E59)
private val cyan_dark_onPrimaryContainer = Color(0xFFA1EFFF)
private val cyan_dark_secondary = Color(0xFFB1CBD1)
private val cyan_dark_onSecondary = Color(0xFF1C3439)
private val cyan_dark_secondaryContainer = Color(0xFF334A50)
private val cyan_dark_onSecondaryContainer = Color(0xFFCDE7ED)
private val cyan_dark_tertiary = Color(0xFFBCC5EB)
private val cyan_dark_onTertiary = Color(0xFF262F4D)
private val cyan_dark_tertiaryContainer = Color(0xFF3C4665)
private val cyan_dark_onTertiaryContainer = Color(0xFFDBE1FF)
private val cyan_dark_error = Color(0xFFFFB4AB)
private val cyan_dark_errorContainer = Color(0xFF93000A)
private val cyan_dark_onError = Color(0xFF690005)
private val cyan_dark_onErrorContainer = Color(0xFFFFDAD6)
private val cyan_dark_background = Color(0xFF191C1D)
private val cyan_dark_onBackground = Color(0xFFE1E3E3)
private val cyan_dark_surface = Color(0xFF191C1D)
private val cyan_dark_onSurface = Color(0xFFE1E3E3)
private val cyan_dark_surfaceVariant = Color(0xFF3F484A)
private val cyan_dark_onSurfaceVariant = Color(0xFFBFC8CA)
private val cyan_dark_outline = Color(0xFF899295)
private val cyan_dark_inverseOnSurface = Color(0xFF191C1D)
private val cyan_dark_inverseSurface = Color(0xFFE1E3E3)
private val cyan_dark_inversePrimary = Color(0xFF006876)
private val cyan_dark_shadow = Color(0xFF000000)
private val cyan_dark_surfaceTint = Color(0xFF44D8F1)

val CyanLightColorScheme = lightColorScheme(
    surfaceTint = cyan_light_surfaceTint,
    onErrorContainer = cyan_light_onErrorContainer,
    onError = cyan_light_onError,
    errorContainer = cyan_light_errorContainer,
    onTertiaryContainer = cyan_light_onTertiaryContainer,
    onTertiary = cyan_light_onTertiary,
    tertiaryContainer = cyan_light_tertiaryContainer,
    tertiary = cyan_light_tertiary,
    error = cyan_light_error,
    outline = cyan_light_outline,
    onBackground = cyan_light_onBackground,
    background = cyan_light_background,
    inverseOnSurface = cyan_light_inverseOnSurface,
    inverseSurface = cyan_light_inverseSurface,
    onSurfaceVariant = cyan_light_onSurfaceVariant,
    onSurface = cyan_light_onSurface,
    surfaceVariant = cyan_light_surfaceVariant,
    surface = cyan_light_surface,
    onSecondaryContainer = cyan_light_onSecondaryContainer,
    onSecondary = cyan_light_onSecondary,
    secondaryContainer = cyan_light_secondaryContainer,
    secondary = cyan_light_secondary,
    inversePrimary = cyan_light_inversePrimary,
    onPrimaryContainer = cyan_light_onPrimaryContainer,
    onPrimary = cyan_light_onPrimary,
    primaryContainer = cyan_light_primaryContainer,
    primary = cyan_light_primary,
)

val CyanDarkColorScheme = darkColorScheme(
    surfaceTint = cyan_dark_surfaceTint,
    onErrorContainer = cyan_dark_onErrorContainer,
    onError = cyan_dark_onError,
    errorContainer = cyan_dark_errorContainer,
    onTertiaryContainer = cyan_dark_onTertiaryContainer,
    onTertiary = cyan_dark_onTertiary,
    tertiaryContainer = cyan_dark_tertiaryContainer,
    tertiary = cyan_dark_tertiary,
    error = cyan_dark_error,
    outline = cyan_dark_outline,
    onBackground = cyan_dark_onBackground,
    background = cyan_dark_background,
    inverseOnSurface = cyan_dark_inverseOnSurface,
    inverseSurface = cyan_dark_inverseSurface,
    onSurfaceVariant = cyan_dark_onSurfaceVariant,
    onSurface = cyan_dark_onSurface,
    surfaceVariant = cyan_dark_surfaceVariant,
    surface = cyan_dark_surface,
    onSecondaryContainer = cyan_dark_onSecondaryContainer,
    onSecondary = cyan_dark_onSecondary,
    secondaryContainer = cyan_dark_secondaryContainer,
    secondary = cyan_dark_secondary,
    inversePrimary = cyan_dark_inversePrimary,
    onPrimaryContainer = cyan_dark_onPrimaryContainer,
    onPrimary = cyan_dark_onPrimary,
    primaryContainer = cyan_dark_primaryContainer,
    primary = cyan_dark_primary,
)