package com.sanmer.mrepo.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val deep_purple_light_primary = Color(0xFF6F43C0)
val deep_purple_light_onPrimary = Color(0xFFFFFFFF)
val deep_purple_light_primaryContainer = Color(0xFFEBDDFF)
val deep_purple_light_onPrimaryContainer = Color(0xFF250059)
val deep_purple_light_secondary = Color(0xFF635B70)
val deep_purple_light_onSecondary = Color(0xFFFFFFFF)
val deep_purple_light_secondaryContainer = Color(0xFFE9DEF8)
val deep_purple_light_onSecondaryContainer = Color(0xFF1F182B)
val deep_purple_light_tertiary = Color(0xFF7E525D)
val deep_purple_light_onTertiary = Color(0xFFFFFFFF)
val deep_purple_light_tertiaryContainer = Color(0xFFFFD9E1)
val deep_purple_light_onTertiaryContainer = Color(0xFF31101B)
val deep_purple_light_error = Color(0xFFBA1A1A)
val deep_purple_light_errorContainer = Color(0xFFFFDAD6)
val deep_purple_light_onError = Color(0xFFFFFFFF)
val deep_purple_light_onErrorContainer = Color(0xFF410002)
val deep_purple_light_background = Color(0xFFFFFBFF)
val deep_purple_light_onBackground = Color(0xFF1D1B1E)
val deep_purple_light_surface = Color(0xFFFFFBFF)
val deep_purple_light_onSurface = Color(0xFF1D1B1E)
val deep_purple_light_surfaceVariant = Color(0xFFE7E0EB)
val deep_purple_light_onSurfaceVariant = Color(0xFF49454E)
val deep_purple_light_outline = Color(0xFF7A757F)
val deep_purple_light_inverseOnSurface = Color(0xFFF5EFF4)
val deep_purple_light_inverseSurface = Color(0xFF323033)
val deep_purple_light_inversePrimary = Color(0xFFD3BBFF)
val deep_purple_light_shadow = Color(0xFF000000)
val deep_purple_light_surfaceTint = Color(0xFF6F43C0)

val deep_purple_dark_primary = Color(0xFFD3BBFF)
val deep_purple_dark_onPrimary = Color(0xFF3F008D)
val deep_purple_dark_primaryContainer = Color(0xFF5727A6)
val deep_purple_dark_onPrimaryContainer = Color(0xFFEBDDFF)
val deep_purple_dark_secondary = Color(0xFFCDC2DB)
val deep_purple_dark_onSecondary = Color(0xFF342D40)
val deep_purple_dark_secondaryContainer = Color(0xFF4B4358)
val deep_purple_dark_onSecondaryContainer = Color(0xFFE9DEF8)
val deep_purple_dark_tertiary = Color(0xFFF0B7C5)
val deep_purple_dark_onTertiary = Color(0xFF4A2530)
val deep_purple_dark_tertiaryContainer = Color(0xFF643B46)
val deep_purple_dark_onTertiaryContainer = Color(0xFFFFD9E1)
val deep_purple_dark_error = Color(0xFFFFB4AB)
val deep_purple_dark_errorContainer = Color(0xFF93000A)
val deep_purple_dark_onError = Color(0xFF690005)
val deep_purple_dark_onErrorContainer = Color(0xFFFFDAD6)
val deep_purple_dark_background = Color(0xFF1D1B1E)
val deep_purple_dark_onBackground = Color(0xFFE6E1E6)
val deep_purple_dark_surface = Color(0xFF1D1B1E)
val deep_purple_dark_onSurface = Color(0xFFE6E1E6)
val deep_purple_dark_surfaceVariant = Color(0xFF49454E)
val deep_purple_dark_onSurfaceVariant = Color(0xFFCBC4CF)
val deep_purple_dark_outline = Color(0xFF948F99)
val deep_purple_dark_inverseOnSurface = Color(0xFF1D1B1E)
val deep_purple_dark_inverseSurface = Color(0xFFE6E1E6)
val deep_purple_dark_inversePrimary = Color(0xFF6F43C0)
val deep_purple_dark_shadow = Color(0xFF000000)
val deep_purple_dark_surfaceTint = Color(0xFFD3BBFF)

val DeepPurpleLightColorScheme = lightColorScheme(
    surfaceTint = deep_purple_light_surfaceTint,
    onErrorContainer = deep_purple_light_onErrorContainer,
    onError = deep_purple_light_onError,
    errorContainer = deep_purple_light_errorContainer,
    onTertiaryContainer = deep_purple_light_onTertiaryContainer,
    onTertiary = deep_purple_light_onTertiary,
    tertiaryContainer = deep_purple_light_tertiaryContainer,
    tertiary = deep_purple_light_tertiary,
    error = deep_purple_light_error,
    outline = deep_purple_light_outline,
    onBackground = deep_purple_light_onBackground,
    background = deep_purple_light_background,
    inverseOnSurface = deep_purple_light_inverseOnSurface,
    inverseSurface = deep_purple_light_inverseSurface,
    onSurfaceVariant = deep_purple_light_onSurfaceVariant,
    onSurface = deep_purple_light_onSurface,
    surfaceVariant = deep_purple_light_surfaceVariant,
    surface = deep_purple_light_surface,
    onSecondaryContainer = deep_purple_light_onSecondaryContainer,
    onSecondary = deep_purple_light_onSecondary,
    secondaryContainer = deep_purple_light_secondaryContainer,
    secondary = deep_purple_light_secondary,
    inversePrimary = deep_purple_light_inversePrimary,
    onPrimaryContainer = deep_purple_light_onPrimaryContainer,
    onPrimary = deep_purple_light_onPrimary,
    primaryContainer = deep_purple_light_primaryContainer,
    primary = deep_purple_light_primary,
)

val DeepPurpleDarkColorScheme = darkColorScheme(
    surfaceTint = deep_purple_dark_surfaceTint,
    onErrorContainer = deep_purple_dark_onErrorContainer,
    onError = deep_purple_dark_onError,
    errorContainer = deep_purple_dark_errorContainer,
    onTertiaryContainer = deep_purple_dark_onTertiaryContainer,
    onTertiary = deep_purple_dark_onTertiary,
    tertiaryContainer = deep_purple_dark_tertiaryContainer,
    tertiary = deep_purple_dark_tertiary,
    error = deep_purple_dark_error,
    outline = deep_purple_dark_outline,
    onBackground = deep_purple_dark_onBackground,
    background = deep_purple_dark_background,
    inverseOnSurface = deep_purple_dark_inverseOnSurface,
    inverseSurface = deep_purple_dark_inverseSurface,
    onSurfaceVariant = deep_purple_dark_onSurfaceVariant,
    onSurface = deep_purple_dark_onSurface,
    surfaceVariant = deep_purple_dark_surfaceVariant,
    surface = deep_purple_dark_surface,
    onSecondaryContainer = deep_purple_dark_onSecondaryContainer,
    onSecondary = deep_purple_dark_onSecondary,
    secondaryContainer = deep_purple_dark_secondaryContainer,
    secondary = deep_purple_dark_secondary,
    inversePrimary = deep_purple_dark_inversePrimary,
    onPrimaryContainer = deep_purple_dark_onPrimaryContainer,
    onPrimary = deep_purple_dark_onPrimary,
    primaryContainer = deep_purple_dark_primaryContainer,
    primary = deep_purple_dark_primary,
)