package com.sanmer.mrepo.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val orange_light_primary = Color(0xFF8B5000)
private val orange_light_onPrimary = Color(0xFFFFFFFF)
private val orange_light_primaryContainer = Color(0xFFFFDCBE)
private val orange_light_onPrimaryContainer = Color(0xFF2C1600)
private val orange_light_secondary = Color(0xFF725A42)
private val orange_light_onSecondary = Color(0xFFFFFFFF)
private val orange_light_secondaryContainer = Color(0xFFFFDCBE)
private val orange_light_onSecondaryContainer = Color(0xFF291806)
private val orange_light_tertiary = Color(0xFF58633A)
private val orange_light_onTertiary = Color(0xFFFFFFFF)
private val orange_light_tertiaryContainer = Color(0xFFDCE8B4)
private val orange_light_onTertiaryContainer = Color(0xFF161E01)
private val orange_light_error = Color(0xFFBA1A1A)
private val orange_light_errorContainer = Color(0xFFFFDAD6)
private val orange_light_onError = Color(0xFFFFFFFF)
private val orange_light_onErrorContainer = Color(0xFF410002)
private val orange_light_background = Color(0xFFFFFBFF)
private val orange_light_onBackground = Color(0xFF201B16)
private val orange_light_surface = Color(0xFFFFFBFF)
private val orange_light_onSurface = Color(0xFF201B16)
private val orange_light_surfaceVariant = Color(0xFFF2DFD1)
private val orange_light_onSurfaceVariant = Color(0xFF51453A)
private val orange_light_outline = Color(0xFF837468)
private val orange_light_inverseOnSurface = Color(0xFFFAEFE7)
private val orange_light_inverseSurface = Color(0xFF352F2B)
private val orange_light_inversePrimary = Color(0xFFFFB870)
private val orange_light_shadow = Color(0xFF000000)
private val orange_light_surfaceTint = Color(0xFF8B5000)

private val orange_dark_primary = Color(0xFFFFB870)
private val orange_dark_onPrimary = Color(0xFF4A2800)
private val orange_dark_primaryContainer = Color(0xFF693C00)
private val orange_dark_onPrimaryContainer = Color(0xFFFFDCBE)
private val orange_dark_secondary = Color(0xFFE1C1A4)
private val orange_dark_onSecondary = Color(0xFF402C18)
private val orange_dark_secondaryContainer = Color(0xFF59422C)
private val orange_dark_onSecondaryContainer = Color(0xFFFFDCBE)
private val orange_dark_tertiary = Color(0xFFC0CC9A)
private val orange_dark_onTertiary = Color(0xFF2B3410)
private val orange_dark_tertiaryContainer = Color(0xFF414B24)
private val orange_dark_onTertiaryContainer = Color(0xFFDCE8B4)
private val orange_dark_error = Color(0xFFFFB4AB)
private val orange_dark_errorContainer = Color(0xFF93000A)
private val orange_dark_onError = Color(0xFF690005)
private val orange_dark_onErrorContainer = Color(0xFFFFDAD6)
private val orange_dark_background = Color(0xFF201B16)
private val orange_dark_onBackground = Color(0xFFEBE0D9)
private val orange_dark_surface = Color(0xFF201B16)
private val orange_dark_onSurface = Color(0xFFEBE0D9)
private val orange_dark_surfaceVariant = Color(0xFF51453A)
private val orange_dark_onSurfaceVariant = Color(0xFFD5C3B5)
private val orange_dark_outline = Color(0xFF9D8E81)
private val orange_dark_inverseOnSurface = Color(0xFF201B16)
private val orange_dark_inverseSurface = Color(0xFFEBE0D9)
private val orange_dark_inversePrimary = Color(0xFF8B5000)
private val orange_dark_shadow = Color(0xFF000000)
private val orange_dark_surfaceTint = Color(0xFFFFB870)

val OrangeLightColorScheme = lightColorScheme(
    surfaceTint = orange_light_surfaceTint,
    onErrorContainer = orange_light_onErrorContainer,
    onError = orange_light_onError,
    errorContainer = orange_light_errorContainer,
    onTertiaryContainer = orange_light_onTertiaryContainer,
    onTertiary = orange_light_onTertiary,
    tertiaryContainer = orange_light_tertiaryContainer,
    tertiary = orange_light_tertiary,
    error = orange_light_error,
    outline = orange_light_outline,
    onBackground = orange_light_onBackground,
    background = orange_light_background,
    inverseOnSurface = orange_light_inverseOnSurface,
    inverseSurface = orange_light_inverseSurface,
    onSurfaceVariant = orange_light_onSurfaceVariant,
    onSurface = orange_light_onSurface,
    surfaceVariant = orange_light_surfaceVariant,
    surface = orange_light_surface,
    onSecondaryContainer = orange_light_onSecondaryContainer,
    onSecondary = orange_light_onSecondary,
    secondaryContainer = orange_light_secondaryContainer,
    secondary = orange_light_secondary,
    inversePrimary = orange_light_inversePrimary,
    onPrimaryContainer = orange_light_onPrimaryContainer,
    onPrimary = orange_light_onPrimary,
    primaryContainer = orange_light_primaryContainer,
    primary = orange_light_primary,
)

val OrangeDarkColorScheme = darkColorScheme(
    surfaceTint = orange_dark_surfaceTint,
    onErrorContainer = orange_dark_onErrorContainer,
    onError = orange_dark_onError,
    errorContainer = orange_dark_errorContainer,
    onTertiaryContainer = orange_dark_onTertiaryContainer,
    onTertiary = orange_dark_onTertiary,
    tertiaryContainer = orange_dark_tertiaryContainer,
    tertiary = orange_dark_tertiary,
    error = orange_dark_error,
    outline = orange_dark_outline,
    onBackground = orange_dark_onBackground,
    background = orange_dark_background,
    inverseOnSurface = orange_dark_inverseOnSurface,
    inverseSurface = orange_dark_inverseSurface,
    onSurfaceVariant = orange_dark_onSurfaceVariant,
    onSurface = orange_dark_onSurface,
    surfaceVariant = orange_dark_surfaceVariant,
    surface = orange_dark_surface,
    onSecondaryContainer = orange_dark_onSecondaryContainer,
    onSecondary = orange_dark_onSecondary,
    secondaryContainer = orange_dark_secondaryContainer,
    secondary = orange_dark_secondary,
    inversePrimary = orange_dark_inversePrimary,
    onPrimaryContainer = orange_dark_onPrimaryContainer,
    onPrimary = orange_dark_onPrimary,
    primaryContainer = orange_dark_primaryContainer,
    primary = orange_dark_primary,
)